/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    docsSidebar: [
        {
            type: 'doc',
            id: 'README', // document ID
            label: 'Getting Started', // sidebar label
        },
        "quick-start",
        {
            type: "category",
            label: "Concepts",
            collapsed: false,
            link: {
                type: "generated-index",
                title: "Concepts",
                description: "Learn about the most important SSI concepts!",
            },
            items: [
                "concepts/identity",
                "concepts/multi-tenancy",
            ],
        },
        {
            type: "category",
            label: "Identus",
            link: {
                type: "generated-index",
                title: "Identus",
                description: "Learn about the Identus ecosystem!",
            },
            collapsed: false,
            items: [
                "identus/overview",
                {
                    type: "category",
                    label: "Cloud Agent",
                    collapsed: true,
                    link: {
                        type: "generated-index",
                        title: "Cloud Agent",
                        description: "Learn about the Identus Cloud Agent!",
                    },
                    items: [
                        "identus/cloud-agent/overview",
                        "identus/cloud-agent/building-blocks",
                        "identus/cloud-agent/authentication",
                        "identus/cloud-agent/did-management",
                        "identus/cloud-agent/secrets-storage",
                        "identus/cloud-agent/environment-variables",
                    ],
                },
                {
                    type: "category",
                    label: "Prism Node",
                    collapsed: true,
                    link: {
                        type: "generated-index",
                        title: "Prism Node",
                        description: "Learn about the Identus Prism Node!",
                    },
                    items: [
                        "identus/prism-node/overview",
                        "identus/prism-node/running-node",
                    ],
                },
                "identus/mediator",
                "identus/troubleshooting&considerations",
                "identus/getting-help",
            ],
        },
        "concepts/glossary",
        "identus/specifications"
    ],
};

module.exports = sidebars;
